import {useEffect, useState}  from "react";
import Head from "next/head";
import axios from 'axios';
import SearchBar from "~/components/searchBar";
import Coinslist from "~/components/coinsList";
import axiosInstance from "~/config/axios";

export default function Home({ backendUrl }) {
  const [coins, setCoins] = useState([]);
  const [filteredCoins, setFilteredCoins] = useState([]);
  
  useEffect(() => {
    async function initialData() {
      const res = await axiosInstance.get('http://localhost:3000/api/proxy/coins');
      setCoins(res.data);
      setFilteredCoins(res.data);
    }
    initialData().then()
  }, [backendUrl])
  
  const handleChange = (e) => {
    e.preventDefault();
    let searchInput = e.target.value.toLowerCase();

    setFilteredCoins(
      coins.filter((coin) =>
        coin.name.toLowerCase().includes(searchInput.toLowerCase())
      )
    )
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="coin_app">
        alo tu smo
        <SearchBar change={handleChange} />
        <Coinslist filteredCoins={filteredCoins} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      backendUrl: process.env.BACKEND_URL
    },
  }
}

//Material Ui https://mui.com